import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import '../../css/style.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Top
// Put any other imports below so that CSS from your
// components takes precedence over default styles.
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {children}</body>
    </html>
  )
}
